# 8. Sympy, Numpy, Scipy, Matplotlib

## Qué es SymPy?

- `SymPy` es una biblioteca de Python para matemáticas simbólicas. 
- Permite realizar cálculos matemáticos exactos, como: álgebra, cálculo, teoría de números y más, de manera simbólica en lugar de numérica.- - Puedes trabajar con expresiones matemáticas como variables, ecuaciones y funciones, en lugar de solo números.

### Características:

1. **Álgebra Simbólica:**
* Simplificación de expresiones algebraicas.
* Expansión y factorización de polinomios.
* Operaciones con fracciones algebraicas.
* Cálculo Diferencial e Integral.
2. **Derivadas y diferenciales.**
* Integrales definidas e indefinidas.
* Series de Taylor.
3. **Resolución de Ecuaciones:**
* Resolver ecuaciones algebraicas y diferenciales.
* Sistemas de ecuaciones lineales y no lineales.
4. **Matrices y Álgebra Lineal:**
* Operaciones con matrices simbólicas.
* Determinantes, inversas y autovalores.
5. **Cálculo Numérico:**
* Evaluación numérica de expresiones simbólicas.
* Conversión de expresiones simbólicas a funciones numéricas.
6. **Gráficas:**
* Representación gráfica de funciones y expresiones.
7. **Soporte para Matemáticas Avanzadas:**
* Teoría de números, combinatoria, geometría, etc.

### Ventajas

1. **Cálculos Exactos**: Trabaja con expresiones simbólicas en lugar de aproximaciones numéricas.
2. **Fácil de Usar**: Tiene una sintaxis intuitiva y está bien documentado.
3. **Independencia de Dependencias**: Es una biblioteca pura de Python, no requiere dependencias externas.
4. **Versatilidad**: Soporta una amplia gama de operaciones matemáticas.

### Instalación

    ! pip install sympy
    import sympy as sp

### Documentación

https://www.sympy.org/en/index.html


### 1. Declarar Variables Simbólicas

In [1]:
from sympy import symbols

# Declarar variables simbólicas
x, y = symbols('x y')
# Crear una expresión simbólica
expr = x**2 + 2*x + 1
print(expr) 

x**2 + 2*x + 1


### 2. Simplificación y expansión de Expresiones 

In [2]:
from sympy import simplify

# Simplificar una expresión
expr = (x**2 + 2*x + 1) / (x + 1)
print(expr)
simplified_expr = simplify(expr)
print(simplified_expr)  

(x**2 + 2*x + 1)/(x + 1)
x + 1


In [3]:
from sympy import expand, sin

expand(sin(x+y), trig=True)

sin(x)*cos(y) + sin(y)*cos(x)

### 3. Derivadas

In [4]:
from sympy import diff

# Derivar una función
f = x**3 + 3*x**2 + 5
print(f)
derivada = diff(f, x)
print(derivada)

x**3 + 3*x**2 + 5
3*x**2 + 6*x


### 4. Integrales


In [5]:
from sympy import integrate

# Integral indefinida
integral_indef = integrate(x**2, x)
print(integral_indef) 

# Integral definida en un intervalo
integral_def = integrate(x**2, (x, 0, 2))
print(integral_def) 

x**3/3
8/3


In [6]:
#también se pueden hacer integrales definidas en infinito
from sympy import oo

integral_inf = integrate(x**2, (x, 0, oo))
print(integral_inf)

oo


5. Series de Taylor

In [7]:
from sympy import symbols, exp, sin, cos
t = symbols('t')
f = exp(sin(t))
f.series(t, 0, 8)

1 + t + t**2/2 - t**4/8 - t**5/15 - t**6/240 + t**7/90 + O(t**8)

y exportar la respuesta en formato **Latex**

In [8]:
from sympy import latex
print (latex(f.series(t, 0, 8)))

1 + t + \frac{t^{2}}{2} - \frac{t^{4}}{8} - \frac{t^{5}}{15} - \frac{t^{6}}{240} + \frac{t^{7}}{90} + O\left(t^{8}\right)


### 6. Resolver Ecuaciones

In [9]:
from sympy import Eq, solve

# Resolver una ecuación algebraica
ecuacion = Eq(x**2 - 4, 0)
soluciones = solve(ecuacion, x)
print(soluciones) 

[-2, 2]


### 7. Operaciones con Matrices


In [10]:
from sympy import Matrix

# Crear una matriz simbólica
A = Matrix([[1, 2], [3, 4]])
print(A)

# Calcular el determinante
determinante = A.det()
print(determinante)

# Calcular la inversa
inversa = A.inv()
print(inversa)

Matrix([[1, 2], [3, 4]])
-2
Matrix([[-2, 1], [3/2, -1/2]])


### 8. Evaluación Numérica


In [11]:
from sympy import pi, sin

# Evaluar una expresión simbólica numéricamente
expr = sin(pi / 4)
valor = expr.evalf()
print(valor) 

0.707106781186548


## ¿Qué es NumPy y por qué usarlo en lugar de listas de Python?

`NumPy` (Numerical Python) es una biblioteca para el cómputo científico. Proporciona:

1. Arreglos multidimensionales (arrays) y matrices, que son estructuras de datos más eficientes que las listas de Python para operaciones numéricas.
2. Funciones matemáticas optimizadas para realizar cálculos rápidos sobre estos arreglos.
3. Herramientas avanzadas para álgebra lineal, transformadas de Fourier, generación de números aleatorios, entre otras.

Aunque las listas de Python son versátiles, NumPy ofrece varias ventajas significativas para cálculos numéricos y científicos:

1. Eficiencia: Los arreglos de NumPy son más rápidos y consumen menos memoria que las listas de Python.
NumPy utiliza implementaciones en C y Fortran, lo que lo hace mucho más eficiente para operaciones matemáticas.
2. Operaciones Vectorizadas: NumPy permite realizar operaciones matemáticas directamente sobre arreglos completos sin necesidad de bucles explícitos.

## Instalación de NumPy.

    ! pip install numpy

## Lista

Una lista en Python es una colección ordenada de elementos que puede contener diferentes tipos de datos (por ejemplo, enteros, cadenas, flotantes, etc.).

1. Flexibilidad: Las listas son muy flexibles, ya que pueden contener elementos heterogéneos (por ejemplo, [1, "texto", 3.14]).
2. Operaciones Matemáticas: **No soportan operaciones** matemáticas vectorizadas.

In [12]:
arr1 = [1, 2, 3, 4, 5] # Crear una lista
print(arr1) # Imprimir la lista
print(type(arr1)) # Imprimir el tipo de dato de la lista
print(2*arr1) # Multiplicar la lista por 2

[1, 2, 3, 4, 5]
<class 'list'>
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [13]:
#bucle
for i in arr1:
    print(2*i)

2
4
6
8
10


## Numpy

Un arreglo de NumPy es una estructura de datos optimizada para cálculos numéricos. Todos los elementos del arreglo deben ser del mismo tipo (por ejemplo, enteros o flotantes).
1. Eficiencia: Los arreglos de NumPy son más rápidos y consumen menos memoria que las listas de Python, ya que están implementados en C.
2. Operaciones Matemáticas: Soportan operaciones matemáticas vectorizadas, lo que significa que puedes realizar operaciones directamente sobre todos los elementos del arreglo sin necesidad de bucles

In [14]:
import numpy as np # Importar la librería numpy

arr2 = np.array(arr1) # Convertir la lista en un array
print(arr2) # Imprimir el array
print(type(arr2)) # Imprimir el tipo de dato del array
print(2*arr2) # Multiplicar el array por 2

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]


Diferencias Clave


| Característica |	Lista de Python (`list`) |	Arreglo de NumPy (`numpy.ndarray`) |
|---|---|---|
| Tipo de datos |	Puede contener elementos de diferentes tipos. |	Todos los elementos deben ser del mismo tipo. |
| Eficiencia |	Menos eficiente en operaciones numéricas. |	Más eficiente, ya que está optimizado para cálculos numéricos. |
| Operaciones matemáticas |	No soporta operaciones vectorizadas. |	Soporta operaciones vectorizadas directamente. |
| Uso en cálculos científicos |	No es ideal para cálculos numéricos avanzados. |	Ideal para cálculos científicos y numéricos. |
 Memoria |	Consume más memoria. |	Consume menos memoria.

## Tipos de datos en arrays (`dtype`).

En NumPy, los arreglos (`numpy.ndarray`) pueden contener datos de diferentes tipos, y el tipo de dato de un arreglo se especifica mediante el atributo `dtype`. Este atributo define el tipo de los elementos almacenados en el arreglo, como enteros, flotantes, cadenas, etc.

El atributo `dtype` en NumPy es crucial para definir y trabajar con el tipo de datos en un arreglo. Esto permite optimizar el uso de memoria y realizar cálculos numéricos de manera eficiente. Puedes especificar el tipo de dato al crear un arreglo o cambiarlo posteriormente según sea necesario.

### Tipos de Datos Comunes en NumPy (dtype)

| Tipo de Dato |	Descripción |
| --- | --- |
| int8 | Enteros de 8 bits (rango: -128 a 127).     
| int16	| Enteros de 16 bits (rango: -32,768 a 32,767).     
| int32 | Enteros de 32 bits (rango: -2,147,483,648 a 2,147,483,647). |
| int64	| Enteros de 64 bits (rango: -9,223,372,036,854,775,808 a 9,223,372,036,854,775,807). |
| uint8	| Enteros sin signo de 8 bits (rango: 0 a 255). |
| uint16 |	Enteros sin signo de 16 bits (rango: 0 a 65,535). |
| uint32 |	Enteros sin signo de 32 bits (rango: 0 a 4,294,967,295). |
| uint64 |	Enteros sin signo de 64 bits (rango: 0 a 18,446,744,073,709,551,615). |
| float16 |	Flotantes de 16 bits (precisión reducida). |
| float32 |	Flotantes de 32 bits (precisión simple). |
| float64 |	Flotantes de 64 bits (precisión doble, este es el tipo por defecto para flotantes). |
| complex64 |	Números complejos de 64 bits (32 bits para la parte real y 32 bits para la parte imaginaria). |
| complex128 |	Números complejos de 128 bits (64 bits para la parte real y 64 bits para la parte imaginaria). |
| bool |	Valores booleanos (True o False). |
| str o U |	Cadenas de texto Unicode. |
| object |	Objetos de Python (pueden contener cualquier tipo de dato). |

In [15]:
# Crear un arreglo de enteros
arr_int = np.array([1, 2, 3], dtype='int32')
print(arr_int) 
print(arr_int.dtype) 

# Crear un arreglo de flotantes
arr_float = np.array([1.5, 2.5, 3.5], dtype='float64')
print(arr_float)  
print(arr_float.dtype) 

# Crear un arreglo de booleanos
arr_bool = np.array([0, 1, 2], dtype='bool')
print(arr_bool)  
print(arr_bool.dtype) 

# Crear un arreglo de cadenas
arr_str = np.array([1, 2, 3], dtype='str')
print(arr_str)  
print(arr_str.dtype)

[1 2 3]
int32
[1.5 2.5 3.5]
float64
[False  True  True]
bool
['1' '2' '3']
<U1


## Creación de arrays

En NumPy, existen varias formas de crear arreglos (`arrays`):

1. `np.array()`

Crea un arreglo a partir de una lista, tupla u otra estructura iterable de Python.

In [16]:

# Crear un arreglo a partir de una lista
arr = np.array([1, 2, 3, 4, 5])
print(arr)  
print(arr.dtype) 

# Crear un arreglo especificando el tipo de dato
arr_float = np.array([1, 2, 3], dtype='float64')
print(arr_float) 

[1 2 3 4 5]
int64
[1. 2. 3.]


2. `np.zeros()`

Crea un arreglo lleno de ceros. Es útil para inicializar arreglos vacíos con valores predeterminados.

    np.zeros(shape, dtype=float)

* `shape`: Una tupla que define las dimensiones del arreglo.
* `dtype`: Tipo de dato de los elementos (opcional, por defecto es float).



In [17]:
# Crear un array de ceros de 3x3
ceros = np.zeros((3,3))
print(ceros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. `np.ones()`

Crea un arreglo lleno de unos. Es útil para inicializar arreglos con valores predeterminados de uno.

    np.ones(shape, dtype=float)

* `shape`: Una tupla que define las dimensiones del arreglo.
* `dtype`: Tipo de dato de los elementos (opcional, por defecto es float).



In [18]:
# Crear un arreglo de unos de 2D
arr_ones_2d = np.ones((3, 2), dtype='int32')
print(arr_ones_2d)

[[1 1]
 [1 1]
 [1 1]]


4. `np.linspace()`

Crea un arreglo con valores igualmente espaciados entre un rango especificado.

    np.linspace(start, stop, num=50, endpoint=True, dtype=None)


* `start`: Valor inicial.
* `stop`: Valor final.
* `num`: Número de valores a generar (por defecto es 50).
* `endpoint`: Si es True, incluye el valor final (stop).
* `dtype`: Tipo de dato de los elementos (opcional).


In [19]:
# Crear un arreglo con 5 valores igualmente espaciados entre 0 y 10
arr_linspace = np.linspace(0, 10, 5)
print(arr_linspace)  
print('')
# Crear un arreglo con 4 valores entre 1 y 2 (sin incluir el valor final)
arr_linspace_no_endpoint = np.linspace(1, 2, 4, endpoint=False)
print(arr_linspace_no_endpoint) 

[ 0.   2.5  5.   7.5 10. ]

[1.   1.25 1.5  1.75]


5. `np.arange()`

Crea un arreglo con valores en un rango especificado, similar a la función `range()` de Python, pero devuelve un arreglo de NumPy.

    np.arange(start, stop, step, dtype=None)

* `start`: Valor inicial (por defecto es 0).
* `stop`: Valor final (no incluido).
* `step`: Incremento entre valores (por defecto es 1).
* `dtype`: Tipo de dato de los elementos (opcional).

In [20]:
# Crear un arreglo de enteros del 0 al 9
arr_arange = np.arange(10)
print(arr_arange)  

# Crear un arreglo con un rango específico
arr_arange_step = np.arange(1, 10, 2)
print(arr_arange_step)  

# Crear un arreglo de flotantes
arr_arange_float = np.arange(0, 1, 0.2)
print(arr_arange_float) 

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.2 0.4 0.6 0.8]


## Cambio de Forma (`reshape`)

El método reshape en NumPy se utiliza para cambiar la forma (dimensiones) de un arreglo sin alterar sus datos. Esto es útil cuando necesitas reorganizar los datos en una estructura diferente, como convertir un arreglo unidimensional en una matriz bidimensional o en un tensor de mayor dimensión

    numpy.reshape(a, newshape)

* `a`: El arreglo original que deseas cambiar de forma.
* `newshape`: Una tupla que especifica la nueva forma del arreglo. 

**El producto de las dimensiones en newshape debe ser igual al número total de elementos en el arreglo original.**

### Reglas Importantes

* **Compatibilidad de Tamaño**: El número total de elementos en el arreglo original debe coincidir con el número total de elementos en la nueva forma.

*Ejemplo*: Un arreglo de 6 elementos puede ser convertido a una forma (2, 3) o (3, 2), pero no a (4, 2).

* **Uso de -1**: Puedes usar -1 en una de las dimensiones de newshape para que NumPy calcule automáticamente el tamaño de esa dimensión.

*Ejemplo*: Si tienes un arreglo de 12 elementos, puedes usar reshape(3, -1) para que NumPy determine que la segunda dimensión debe ser 4.


In [21]:
# Arreglo original
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

# Cambiar a una matriz 2x3
arr_reshaped = arr.reshape(2, 3)
print(arr_reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [22]:
# Cambiar a un tensor 3D de forma (2, 1, 3)
arr_reshaped_3d = arr.reshape(2, 1, 3)
print(arr_reshaped_3d)

[[[1 2 3]]

 [[4 5 6]]]


In [23]:
# Cambiar a una matriz 3x2 usando -1
arr_reshaped_auto = arr.reshape(3, -1)
print(arr_reshaped_auto)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
# Arreglo 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Cambiar a un arreglo 1D
arr_flattened = arr_2d.reshape(-1)
print(arr_flattened)

[1 2 3 4 5 6]


In [25]:
# Esto generará un error porque 6 elementos no pueden ser reorganizados en una forma (4, 2)
# arr_invalid = arr.reshape(4, 2)

### Comparación con resize

* `reshape`: Devuelve un nuevo arreglo con la forma especificada, pero no modifica el arreglo original.
* `resize`: Modifica el arreglo original en su lugar y puede rellenar con ceros si el tamaño no coincide.

In [43]:
# Usando reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print('reshape:')
print(reshaped)  
print(arr)       # El arreglo original no cambia
print('')
print('resize:')
# Usando resize
arr.resize(2, 3)
print(arr)       # El arreglo original cambia

reshape:
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

resize:
[[1 2 3]
 [4 5 6]]


## Indexación y Segmentación 

La indexación y segmentación (slicing) son técnicas fundamentales para acceder y manipular elementos de arreglos en NumPy. Estas herramientas permiten seleccionar elementos individuales, subconjuntos de datos o realizar operaciones avanzadas como filtrado con máscaras booleanas.

### 1. Indexación

La indexación se utiliza para acceder a elementos específicos de un arreglo. Funciona de manera similar a las listas en Python, pero con soporte para múltiples dimensiones.

**Indexación en Arreglos 1D**

    * Los índices comienzan en 0.
    * Puedes acceder a un elemento específico utilizando su posición.

**Indexación en Arreglos 2D**

    * Usa dos índices: [renglon, columna].
    * El primer índice selecciona el renglón y el segundo índice selecciona la columna.

**Indexación en Arreglos 3D**

    * Usa tres índices: [profundidad,renglon, columna].



In [50]:
# Arreglo 1D
arr = np.array([10, 20, 30, 40, 50])

# Acceder al primer elemento
print(arr[0])

# Acceder al último elemento
print(arr[-1]) 

10
50


\begin{align*}
arr\_2d =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} 
\end{align*}

\begin{align*}
arr\_2d =
\begin{bmatrix}
(0,0) & (0,1) & (0,2) \\
(1,0) & (1,1) & (1,2) \\
(2,0) & (2,1) & (2,2) \\
\end{bmatrix} 
\end{align*}

In [113]:
# Arreglo 2D
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Acceder al elemento delrenglon 1, columna 2
print(arr_2d[1, 2]) 

# Acceder al primer renglon  completa
print(arr_2d[0])  

# Acceder a la primera columna completa
print(arr_2d[:,0]) 




6
[1 2 3]
[1 4 7]


In [ ]:
from sympy import Matrix

# Crear una matriz simbólica
A = Matrix([[1, 2], [3, 4]])
print(A)

# Calcular el determinante
determinante = A.det()
print(determinante)

# Calcular la inversa
inversa = A.inv()
print(inversa)

\begin{align*}
T =
\begin{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}, \quad
\begin{bmatrix}
10 & 11 & 12 \\
13 & 14 & 15 \\
16 & 17 & 18
\end{bmatrix}
\end{bmatrix} 
\end{align*}

In [116]:
T = np.array([[[1, 2, 3], 
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12], 
               [13, 14, 15],
               [16, 17, 18]]])
#print(T)
print(T[0])# Primera capa (T(0,:,:)
print(T[1])  # Segunda capa (T(1,:,:))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [118]:
# Acceder al elemento en la segunda capa, segundo renglon, primera columna 

print(T[1, 1, 0])

13


###  2. Segmentación (Slicing)

La segmentación permite seleccionar subconjuntos de elementos de un arreglo utilizando rangos de índices. La sintaxis es similar a las listas en Python: `[inicio:fin:paso]`.

In [120]:
# Arreglo 1D
arr = np.array([10, 20, 30, 40, 50])

# Seleccionar los primeros 3 elementos
print(arr[:3])  

# Seleccionar del índice 1 al 3 (sin incluir el 3)
print(arr[1:3]) 

# Seleccionar cada 2 elementos
print(arr[::2]) 

[10 20 30]
[20 30]
[10 30 50]


In [130]:
# Arreglo 2D
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Seleccionar el primer renglón
print(arr_2d[1:2])
print('')

# Seleccionar la primera columna
print(arr_2d[:,1:2])
print('')

# Seleccionar un subconjunto (fila 1 y 2, columna 1 y 2)
print(arr_2d[1:2, 1:2])

[[4 5 6]]

[[2]
 [5]
 [8]]

[[5]]


In [105]:
# Arreglo 3D
arr_3d = np.array([[[1, 2], 
                    [3, 4]], 
                   [[5, 6], 
                    [7, 8]]])

# Seleccionar la primera "capa"
print(arr_3d[0])
print('')
# Seleccionar el primer renglon  de todas las capas
print(arr_3d[:, 0, :])

[[1 2]
 [3 4]]

[[1 2]
 [5 6]]


In [132]:
# Seleccionar la primera columna de todas las capas
print(arr_3d[:, :, 0])


[[1 3]
 [5 7]]


### 3. Boolean Masking

La máscara booleana permite seleccionar elementos de un arreglo que cumplen una condición específica. Esto es útil para filtrar datos.



In [33]:
# Arreglo 1D
arr = np.array([10, 20, 30, 40, 50])

# Crear una máscara booleana para elementos mayores a 25
mask = arr > 25
print(mask)  

# Usar la máscara para filtrar elementos
print(arr[mask])  

[False False  True  True  True]
[30 40 50]


In [133]:
# Arreglo 2D
arr_2d = np.array([[[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]],
                    [[10, 11, 12], 
                     [13, 14, 15], 
                     [16, 17, 18]]])
                   
# Crear una máscara para elementos mayores a 5
mask = arr_2d > 5
print(mask)


# Filtrar elementos mayores a 5
print(arr_2d[mask])  

[[[False False False]
  [False False  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18]


## Operaciones Matemáticas y Estadísticas
* Operaciones básicas (+, -, *, /).
* Funciones estadísticas (mean, sum, max, min).
* Funciones matemáticas (sin, cos, log).

In [35]:
# Operaciones básicas
arr = np.array([1, 2, 3, 4])
print(arr * 2)

# Cálculo de la media
print(np.mean(arr))

# Aplicación de funciones matemáticas
print(np.sin(arr))


[2 4 6 8]
2.5
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


## Álgebra Lineal en NumPy

* Producto punto (np.dot).
* Matrices identidad y transpuestas.
* Determinante y valores propios.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [134]:
# Producto punto entre matrices
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])
print(np.dot(A, B))

# Matriz identidad
print(np.eye(3))

# Determinante de una matriz
print(np.linalg.det(A))

# Inversa de una matriz
print(np.linalg.inv(A))


[[19 22]
 [43 50]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


## Manipulación Avanzada de Arrays
* Concatenación de arrays.
* Apilamiento de arrays (hstack, vstack).
* Ordenamiento y búsqueda.


In [37]:
# Concatenación de arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate([arr1, arr2]))

# Ordenar un array
arr = np.array([5, 3, 1, 4, 2])
print(np.sort(arr))


[1 2 3 4 5 6]
[1 2 3 4 5]
